### ISSUE TITLE
Timeout issue under high load with DataStax Cassandra driver

### ISSUE THREAD

**Issue by gregjan** [trellis-ldp/trellis-extensions#34]
The error I'm seeing in my stress tests is the same one that occurred earlier when Adam was switching to the DataStax driver. This is a socket write timeout error, where the default value is 2 seconds. The service is showing as performing much slower than previous tests. 

The error:
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed
out after PT2S

I've published the dashboard for the test that produced this error:
http://drastic-testbed.umd.edu:3000/dashboard/snapshot/ySLcL7B7KYnwCaMs0THZDxuo58g1oL8i
If look at it, you can see that response durations start increasing beyond previous tests right away. Then failures begin after about a minute and a half.

Here is the full stack trace:
https://gist.github.com/gregjan/1a1a7e752384b30604eb030e693b5bbb

**Comment by gregjan** [comment]
From Adam: Aaron, did you make changes to the management of asynchrony in the move or afterwards? That's what that is a symptom of-- it could be a deadlock from calling a synch C* driver method in a callback from an async C* driver method. For example, call for a binary, then in the callback, get its bits.

**Comment by gregjan** [comment]
FYI, a test with just one worker node (2000 users) produces no errors
whatsoever. So it's showing up as a result of higher load at least.
http://drastic-testbed.umd.edu:3000/dashboard/snapshot/W4sSsJ1Q3k9klGKECom3BWMRu5VQkz1T

**Comment by gregjan** [comment]
From Aaron: Adam, I made the async changes after moving the code from the trellis-cassandra repo. The sort of changes are highlighted in this commit:

https://github.com/trellis-ldp/trellis-extensions/commit/812cc446eb698363397100971b17c639a7f023bc#diff-c25162ad58db7a7d2768ae3681b24b59L70-L83

If anything, the changes were moving from sync queries to async queries. When we were running these tests ourselves a few weeks ago we were encountering (possibly?) similar issues with client timeouts. It seemed like connections might not be getting closed or some other sort of resource left open.

**Comment by gregjan** [comment]
From Adam: What I can tell you now is that if you have removed the code I wrote to make sure that the same thread pool is not being used for retrieving binaries _and_ their bitstreams, that certainly could cause this, even with fully asynchronous calls, and it would appear more quickly under load (exhausting the single threadpool into deadlock).

**Comment by gregjan** [comment]
From Adam:
The code was in BinaryService::get. The needful incantation was to use the two parameter form of ::thenApplyAsync at

https://github.com/trellis-ldp/trellis-extensions/blob/master/cassandra/src/main/java/org/trellisldp/ext/cassandra/CassandraBinaryService.java#L110

supplying a separate threadpool to ensure that any later pushing of the bitstream from the server-side (not the client ultimately reading the stream) uses that separate threadpool ('readBinaryWorkers') there. That eliminated the problem for me and at CI, although it is certainly possible that something more complex is happening now, of course.

**Comment by acoburn** [comment]
@gregjan This is a little challenging to debug. If you are in a position to [enable metrics](https://docs.datastax.com/en/developer/java-driver/4.2/manual/core/pooling/#monitoring) on your Cassandra cluster and see whether the `pool.available-streams` value is what you would expect?

**Comment by gregjan** [comment]
I am still traveling, presenting and meeting for the remainder of this
week, but I will try and set up a test run with this enabled and then
gather some logs. These logs will be quite large I think, but such is life.

**Comment by ajs6f** [comment]
I think @acoburn has the right idea. I suspect strongly that this is going to turn out to be about deadlocking, but I admit that I don't know where or how. The threadpools I set up in the original code are hardcoded via `Executors::newCachedThreadPool`, which is fairly brainless, but also shouldn't exhaust except if something really strange is happening, something weird inside the JVM. With µprofile on-line perhaps [they can be injected](https://projects.eclipse.org/projects/technology.microprofile/releases/context-propagation-1.0) instead to provide some tune-ability and metrics?

In any event, I suspect (is this why you asked for C* metrics @acoburn?) that the problem is closer to or actually in the driver. I suspect Trellis has found some way to accidentally pull a future into the present (aka synchronizing) inside a callback. I _thought_ I had eliminated all the possible places that could happen; famous last words. It's also possible (although I don't see where it could happen) that the HTTP layer is calling `::join` or `::get` on a `CompletableFuture` and triggering the problem that way, but I don't see how we could do that without it being explicit in the code.

I idly wonder if https://github.com/trellis-ldp/trellis/pull/615 might have any effect on this.

**Comment by gregjan** [comment]
Trying to add monitoring now. I noticed this about connection pools in 4.2:

"Unlike previous versions of the driver, pools do not resize dynamically. However you can adjust the options at runtime, the driver will detect and apply the changes."
  
Is that where your suspicion arises?

**Comment by acoburn** [comment]
@gregjan yes, that was part of my line of thinking. It just seems that the connection pools are getting flooded and my hypothesis was that either they are set too low in the first place or they aren't growing in response to heavy load

**Comment by ajs6f** [comment]
Sounds _extremely_ plausible to me.

**Comment by gregjan** [comment]
an update:
I tried turning on driver monitoring of open/available connections, but this was a hard fail. Docker is refusing to allow the application to upgrade thread priorities (or something), giving an mbind error. When I removed the monitoring config it worked again. I doubled the connections per node to 2 instead of 1 and I am testing that now. It already worked at 1 tester node, but that was working before. So. Now I am proceeding with a 4 node test against that config (2 driver connections per node).

**Comment by gregjan** [comment]
So far I have only managed to reproduce the error under the high load of 4 test workers. I tried 10 connections per node, so next I'll try increasing max requests per connection.. I don't want to adjust the timeout yet, since the older driver was able to handle this load somehow with the same default timeout.

**Comment by ajs6f** [comment]
I agree with your take, @gregjan; we should really make sure we are sure that the threadpooling is sane before going anywhere near timeouts. When I first saw this kind of thing pop up months ago, it had nothing to do with timeouts and everything to do with thread context, but I pushed timeouts sky-high to check and got nothing done that way.

**Comment by gregjan** [comment]
None of the driver settings have changed the overall pattern we've been seeing under high load. I tried and failed to fix the monitoring issue with some docker settings. So, I'm turning back to the code to try a few changes locally. Will let you know if I made any headway.

**Comment by gregjan** [comment]
I just did a stress test after having back out the async changes in this commit:  trellis-ldp/trellis#615  (based on latest 0.9.4-SNAPSHOT)
Unfortunately that did not yield a different result. So I'm still hunting around for clues.
